ChromeURL=https://customer-portal-uat.equentisinvestech.com/
email=vijoy.sharma97@gmail.com
mobile=9903171719
profile.menu.items=Profile,FAQs,About us,Contact us,Log Out
expected.email.validationmsg=No account found with the provided details. Please verify and try again or contact us for assistance.
expected.otp.validationmsg=Invalid OTP. Please try again.
invalidcompName=XYZ
company=Apollo 
StockQty=1000